<a href="https://colab.research.google.com/github/dangtrantanluc/MachineLearning/blob/main/TrainingMLModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**House Price Prediction Project**


1.   Problem Definition
*   price for each house
*
2.   Feature Selection:
*   Choose feature to train ML model
*   Need to use 'Feature Engineering to identify Features needed
3.   Splitting the datasets**
3.1   dataset -> x,y
*   data: dataset
*   x: data[features]
*   y: target variable SalePrice
3.2   x, y -> x_train, y_train , x_valid, y_valid
4. Training Machine Learning Model








In [7]:
import pandas as pd
import numpy as np

In [11]:
data_df = pd.read_csv("train.csv")

In [12]:
data_df.head()

Id  MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
0   1          60       RL         65.0     8450   Pave   NaN      Reg   
1   2          20       RL         80.0     9600   Pave   NaN      Reg   
2   3          60       RL         68.0    11250   Pave   NaN      IR1   
3   4          70       RL         60.0     9550   Pave   NaN      IR1   
4   5          60       RL         84.0    14260   Pave   NaN      IR1   

  LandContour Utilities  ... PoolArea PoolQC Fence MiscFeature MiscVal MoSold  \
0         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
1         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      5   
2         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      9   
3         Lvl    AllPub  ...        0    NaN   NaN         NaN       0      2   
4         Lvl    AllPub  ...        0    NaN   NaN         NaN       0     12   

  YrSold  SaleType  SaleCondition  SalePrice  
0   2008        WD         Normal     208500  
1   2007        WD         Normal     181500  
2   2008        WD         Normal     223500  
3   2006        WD        Abnorml     140000  
4   2008        WD         Normal     250000  

[5 rows x 81 columns]

In [14]:
data_df = pd.read_csv("train.csv", index_col="Id")

In [15]:
data_df.head()

MSSubClass MSZoning  LotFrontage  LotArea Street Alley LotShape  \
Id                                                                    
1           60       RL         65.0     8450   Pave   NaN      Reg   
2           20       RL         80.0     9600   Pave   NaN      Reg   
3           60       RL         68.0    11250   Pave   NaN      IR1   
4           70       RL         60.0     9550   Pave   NaN      IR1   
5           60       RL         84.0    14260   Pave   NaN      IR1   

   LandContour Utilities LotConfig  ... PoolArea PoolQC Fence MiscFeature  \
Id                                  ...                                     
1          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
2          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   
3          Lvl    AllPub    Inside  ...        0    NaN   NaN         NaN   
4          Lvl    AllPub    Corner  ...        0    NaN   NaN         NaN   
5          Lvl    AllPub       FR2  ...        0    NaN   NaN         NaN   

   MiscVal MoSold  YrSold  SaleType  SaleCondition  SalePrice  
Id                                                             
1        0      2    2008        WD         Normal     208500  
2        0      5    2007        WD         Normal     181500  
3        0      9    2008        WD         Normal     223500  
4        0      2    2006        WD        Abnorml     140000  
5        0     12    2008        WD         Normal     250000  

[5 rows x 80 columns]

In [19]:
features  = ["LotArea", "YearBuilt", "1stFlrSF", "2ndFlrSF", "FullBath", "BedroomAbvGr", "TotRmsAbvGrd"]

In [24]:
x =data_df[features]
y = data_df["SalePrice"]

In [22]:
x.head()

LotArea  YearBuilt  1stFlrSF  2ndFlrSF  FullBath  BedroomAbvGr  \
Id                                                                   
1      8450       2003       856       854         2             3   
2      9600       1976      1262         0         2             3   
3     11250       2001       920       866         2             3   
4      9550       1915       961       756         1             3   
5     14260       2000      1145      1053         2             4   

    TotRmsAbvGrd  
Id                
1              8  
2              6  
3              6  
4              7  
5              9

In [26]:
y.head()

Id
1    208500
2    181500
3    223500
4    140000
5    250000
Name: SalePrice, dtype: int64

In [47]:
from sklearn.model_selection import train_test_split

x_train, x_valid ,y_train, y_valid = train_test_split(x, y, train_size=0.8, test_size=0.2, random_state=0)

In [31]:
x_train.shape

(1168, 7)

In [34]:
x.shape

(1460, 7)

In [37]:
data_df.shape

(1460, 80)

In [48]:
x_valid.shape

(292, 7)

In [40]:
from sklearn.tree import DecisionTreeRegressor
dt_model = DecisionTreeRegressor(random_state=1)

In [49]:
#fit training data into model
dt_model.fit(x_train, y_train)

DecisionTreeRegressor(random_state=1)

In [52]:
y_pre = dt_model.predict(x_valid.head())

In [54]:
y_pre

array([335000., 140200., 119000., 207500., 112000.])

In [56]:
pd.DataFrame({'y': y_valid.head(), 'y_pre': y_pre})

y     y_pre
Id                   
530  200624  335000.0
492  133000  140200.0
460  110000  119000.0
280  192000  207500.0
656   88000  112000.0

In [58]:
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
rf_model = RandomForestRegressor(random_state=1)
rf_model.fit(x_train, y_train)

RandomForestRegressor(random_state=1)

In [59]:
rf_val_pre = rf_model.predict(x_valid)

In [60]:
rf_val_pre[:5]

array([271690., 155039., 122024., 188915.,  91147.])

In [61]:
rf_model.predict([[6969,2021,1000,800,4,5,8]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:465: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


array([206158.4])